### ISSUE TITLE
Not compatible with Python2

### ISSUE THREAD

**Issue by ysinjab** [kjam/data-pipelines-course#2]
Hi,

After creating python2 virtual environment, and then trying to pip install requirements.txt , an error showed:

```
Collecting jupyterhub==0.6.1 (from -r requirements.txt (line 64))
  Using cached jupyterhub-0.6.1.tar.gz
    Complete output from command python setup.py egg_info:
    ERROR: Jupyter Hub requires Python version 3.3 or above.   

```
Clearly JupyterHub has a requirement that it is only compatible with Python >= 3.3

Thanks !

**Comment by kjam** [comment]
Hi there,

Jupyterhub is not needed to run the notebooks, you can just use Jupyter! I will update the requirements file to reflect that.

Thanks!
-kj
